- name: GitLab
  href: https://gitlab.spack.io/

- name: CDash
  href: https://cdash.spack.io/

- name: Grafana
  href: https://grafana.spack.io/

- name: Prometheus
  href: https://prometheus.spack.io/

- name: Metabase
  href: https://metabase.spack.io/
